### ISSUE TITLE
Uncaught TypeError: Cannot read property '101' of undefined

### ISSUE THREAD

**Issue by simonspa** [grischa/atom-emacs-tab#3] opened 2017-08-14 14:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [emacs-tab](https://github.com/grischa/atom-emacs-tab) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '101' of undefined

```
At /home/simonspa/cloud/configs/.atom/packages/emacs-tab/lib/emacs-flow.coffee:17

TypeError: Cannot read property '101' of undefined
    at EmacsFlow.module.exports.EmacsFlow.autoIndent (/packages/emacs-tab/lib/emacs-flow.coffee:17:40)
    at /packages/emacs-tab/lib/index.coffee:14:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:35)
    at /opt/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:13.7.0 core:delete (input.hidden-input)
     -0:13.5.0 emacs-flow:auto-indent (input.hidden-input)
     -0:06.7.0 core:move-down (input.hidden-input)
     -0:06.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:05.9.0 core:delete (input.hidden-input)
     -0:05.7.0 core:move-down (input.hidden-input)
     -0:05.5.0 core:delete (input.hidden-input)
     -0:05.2.0 core:move-down (input.hidden-input)
     -0:05.0 core:delete (input.hidden-input)
     -0:04.8.0 core:move-down (input.hidden-input)
     -0:04.6.0 core:delete (input.hidden-input)
     -0:04.3.0 core:move-down (input.hidden-input)
     -0:04.1.0 core:delete (input.hidden-input)
     -0:03.9.0 core:move-down (input.hidden-input)
     -0:03.7.0 core:delete (input.hidden-input)
     -0:03.4.0 emacs-flow:auto-indent (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atomic-emacs 0.12.0 
emacs-tab 0.1.0 
gitlab-integration 0.4.0 
gtk-dark-theme 0.1.4 
language-cmake 0.3.0 
language-latex 1.1.0 
language-markdown 0.25.1 
markdown-preview-opener 0.1.1 
markdown-preview-plus 2.4.10 
project-plus 1.0.0 
tablr 1.8.3 
theme-switcher 1.1.0 
wordcount 2.10.4 
```

**Comment by messju** [comment] 2017-08-15 13:57
Seems to be a duplicate of #2

**Comment by grischa** [comment] 2017-08-17 02:14
Fixed now, thanks

**Closed as completed by grischa** 2017-08-17 02:14 UTC
